### ISSUE TITLE
Animekisa video direct links not working

### ISSUE THREAD

**Issue by ExoTixWereWolf** [samuelmaddock/metastream#134] opened 2019-07-06 16:40 UTC
https://animekisa.tv/

Working playback controls:
- [ ] Play/pause
- [ ] Seek
- [ ] Volume

Test URLs:

https://animekisa.tv/fruits-basket-2019-episode-14

Adding it to meta, you'll get an error page or a error message in MetaStream. 
You can Open the link out of meta and right click the video t o copy video address and it will work. The actual sites url worked until recently
![2019-07-06 12_39_10-Metastream](https://user-images.githubusercontent.com/50385637/60758938-32cdf480-9feb-11e9-8656-58abde3c57ad.png)
![2019-07-06 12_39_27-Metastream](https://user-images.githubusercontent.com/50385637/60758941-3b262f80-9feb-11e9-96f5-99517c1f5242.png)
![2019-07-06 12_39_36-Metastream](https://user-images.githubusercontent.com/50385637/60758942-3feae380-9feb-11e9-8048-bc46cea778f9.png)

**Comment by samuelmaddock** [comment] 2019-07-06 17:15
This is caused by Chrome extension's request throttling. When the link is requested, Metastream tries to scrape the website for metadata. It returns a 503 error for that site which triggers the request throttling. https://dev.chromium.org/throttling

Instead of giving the request error when Metastream fails to get metadata, I'm going to change it to add the link without a proper title.

**Comment by samuelmaddock** [comment] 2019-07-06 21:11
Fixed in v0.3.12 https://github.com/samuelmaddock/metastream/releases/tag/v0.3.12

**Closed by samuelmaddock** 2019-07-06 21:11 UTC
