### ISSUE TITLE
Netflix login issue

### ISSUE THREAD

**Issue by blinkdage** [samuelmaddock/metastream#246] opened 2020-02-27 19:26 UTC
- Metastream Version: 0.40
- Browser + Version: Chrome-- Version 80.0.3987.122 (Official Build) (64-bit)
                                  Firefox-- Version 73.0.1 
- OS Version: Win10 Home

Steps to Reproduce:

1. Used Metastream App, Metastream site on Chrome/Firefox, and Netflix.com on Chrome/Firefox (versions above)
2. Could log into Netflix.com, but not through any version of Metastream available. 
3. When attempting to log in, I get redirected to the log-in page.
4. Extension has full permission to access all sites.
5. Upon trying to log-in my email gets the "Netflix new log-in" automated email, so it seems the request is being sent. 
6. Restarting the PC or using a Private Window did not change this. 
7. Other websites like YouTube still work when adding to session. 

This worked fine yesterday 02.26.20. I'm not sure what changed.

**Comment by Sikatsu** [comment] 2020-02-27 22:42
Having the same issue, it worked fine yesterday indeed.

**Comment by samuelmaddock** [comment] 2020-02-28 05:57
This is caused by Netflix enforcing a [Same-Site cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_cookies). I'll be releasing an update with a "fix" tomorrow. I'm enabling a new feature to allow watching in a popup (#197). Netflix will need to use this popup player to work.

**Comment by Sikatsu** [comment] 2020-02-28 10:59
I did try to disable it as suggested in the chrome flags, but that didn't solve it this time.

Thanks for working on it, metastream is the best platform out there now rabbit is no longer available.

**Comment by blinkdage** [comment] 2020-02-28 14:58
Thank you so much for working on this. It is appreciated. 

My friends and I are all using our individual Netflix accounts to watch shows together and this site offers a fantastic tool to use our accounts simultaneously.

**Comment by samuelmaddock** [comment] 2020-02-29 03:11
A workaround was released in v0.7.0 (a popup player #197).

See announcement in Discord for more details.
https://discordapp.com/channels/417584997533483009/479433147637956608/683145838369046552

**Closed by samuelmaddock** 2020-02-29 03:11 UTC
