### ISSUE TITLE
Metastream in opera blocks google searches

### ISSUE THREAD

**Issue by ExoTixWereWolf** [samuelmaddock/metastream#139] opened 2019-07-08 00:48 UTC
- Metastream Version: 0.3.12
- Browser + Version:Opera - 62.0.3331.43
- OS Version:Windows 10

Steps to Reproduce:

1.Just pressing + and clicking google. 
2.You can get to google, but searching is blocked after.

I've went through all extension settings and security features for anyting blocking requests or redirects to 3rd party cookies.I am still able to use it out of meta to get my links, So, no big deal. Just a bug unless im doing anything wrong
![2019-07-07 20_43_06-Window](https://user-images.githubusercontent.com/50385637/60776195-43b85c00-a0f8-11e9-83ad-affcfad85ecb.png)

**Comment by samuelmaddock** [comment] 2019-07-08 01:14
This is a duplicate of #135

**Closed by samuelmaddock** 2019-07-08 01:14 UTC
