### ISSUE TITLE
Have option to remove "up next" box

### ISSUE THREAD

**Issue by suyashori** [samuelmaddock/metastream#201] opened 2019-08-30 00:12 UTC
Up next won't go away while we're watching movie. Also maybe have accounts in meta stream?

**Comment by samuelmaddock** [comment] 2019-08-30 00:21
Duplicate of #157

> Also maybe have accounts in meta stream?

Please create a separate thread for each request. Also it would be helpful to know what benefits accounts could bring.

**Closed by samuelmaddock** 2019-08-30 00:21 UTC
Labels: duplicate
